/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forme;

/**
 *
 * @author Petkovic
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        setTitle("Prijava");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUlogovani = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miKreirajRezervaciju = new javax.swing.JMenuItem();
        miPrikazRezervacija = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miPrikazGostiju = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miUbaciSmenu = new javax.swing.JMenuItem();
        miPretraziSmenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 240, 241));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        lblUlogovani.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUlogovani.setForeground(new java.awt.Color(255, 255, 255));
        lblUlogovani.setText("Zdravo");

        jLabel1.setForeground(new java.awt.Color(189, 195, 199));
        jLabel1.setText("Sistem za praćenje rezervacija");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        jMenu1.setText("Rezervacije");

        miKreirajRezervaciju.setText("Kreiraj rezervaciju");
        miKreirajRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajRezervacijuActionPerformed(evt);
            }
        });
        jMenu1.add(miKreirajRezervaciju);

        miPrikazRezervacija.setText("Prikaz rezervacija");
        jMenu1.add(miPrikazRezervacija);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gosti");

        miPrikazGostiju.setText("Prikaz gostiju");
        jMenu2.add(miPrikazGostiju);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Smene");

        miUbaciSmenu.setText("Ubaci smenu");
        jMenu3.add(miUbaciSmenu);

        miPretraziSmenu.setText("Pretraži smenu");
        miPretraziSmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziSmenuActionPerformed(evt);
            }
        });
        jMenu3.add(miPretraziSmenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miKreirajRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajRezervacijuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miKreirajRezervacijuActionPerformed

    private void miPretraziSmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziSmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretraziSmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miKreirajRezervaciju;
    private javax.swing.JMenuItem miPretraziSmenu;
    private javax.swing.JMenuItem miPrikazGostiju;
    private javax.swing.JMenuItem miPrikazRezervacija;
    private javax.swing.JMenuItem miUbaciSmenu;
    // End of variables declaration//GEN-END:variables


    public javax.swing.JMenuItem getMiKreirajRezervaciju() {
        return miKreirajRezervaciju;
    }
    public javax.swing.JMenuItem getMiPrikazRezervacija() {
        return miPrikazRezervacija;
    }
    public javax.swing.JMenuItem getMiPrikazGostiju() {
        return miPrikazGostiju;
    }
    public javax.swing.JMenuItem getMiUbaciSmenu() {
        return miUbaciSmenu;
    }
   
    public javax.swing.JLabel getLblUlogovani() {
        return lblUlogovani;
    }

    public javax.swing.JMenuItem getMiPretraziSmenu() {
        return miPretraziSmenu;
    }

}
