
package Komunikacija;

import java.io.Serializable;

public enum Operacija implements Serializable {
    LOGIN,
    UCITAJ_MESTA, KREIRAJ_MESTO, PROMENI_MESTO, OBRISI_MESTO, PRETRAZI_MESTO,
    UCITAJ_STOLOVE, KREIRAJ_STO, PROMENI_STO, OBRISI_STO, PRETRAZI_STO,
    UCITAJ_SMENE, UBACI_SMENU, PROMENI_SMENU, OBRISI_SMENU, PRETRAZI_SMENU,
    UCITAJ_ZAPOSLENE, KREIRAJ_ZAPOSLENOG, PROMENI_ZAPOSLENOG, OBRISI_ZAPOSLENOG, PRETRAZI_ZAPOSLENOG,
    UCITAJ_GOSTE, KREIRAJ_GOSTA, PROMENI_GOSTA, OBRISI_GOSTA, PRETRAZI_GOSTA,
    UCITAJ_REZERVACIJE, KREIRAJ_REZERVACIJU, PROMENI_REZERVACIJU, PRETRAZI_REZERVACIJU; 
}
